name: 监听

on:
  schedule:
    # 每小时10分都执行一次
    - cron: '10 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: 22
        
      - name: 初始化-安装node
        id: build
        run: |
          npm install

      - name: 开始
        id: run
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          node index.js
